kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-common-service-webhook
subjects:
  - kind: ServiceAccount
    name: ibm-common-service-webhook
    namespace: ibm-common-services
roleRef:
  kind: ClusterRole
  name: ibm-common-service-webhook
  apiGroup: rbac.authorization.k8s.io
